// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AudioPlayerController from "./audio_player_controller"
application.register("audio-player", AudioPlayerController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import QaCardController from "./qa_card_controller"
application.register("qa-card", QaCardController)

import QuizController from "./quiz_controller"
application.register("quiz", QuizController)
