name: Rails CI (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the stack
        run: docker compose build

      - name: Start database
        run: docker compose up -d db

      - name: Set up database
        run: |
          docker compose run --rm web bundle exec rails db:create
          docker compose run --rm web bundle exec rails db:schema:load

      - name: Run RSpec
        run: docker compose run --rm web bundle exec rspec
